export enum GameState {
  SCENE_INTRO = 'SCENE_INTRO',
  DECISION_WINDOW = 'DECISION_WINDOW',
  OUTCOME_TAP = 'OUTCOME_TAP',
  FIGHT_INIT = 'FIGHT_INIT',
  FIGHT_ACTIVE = 'FIGHT_ACTIVE',
  FIGHT_OUTCOME = 'FIGHT_OUTCOME',
  SCENE_END = 'SCENE_END',
  GAME_OVER = 'GAME_OVER',
  GAME_WIN = 'GAME_WIN',
}
